### ISSUE TITLE
bot trooper cogs

### ISSUE THREAD

**Issue by pbprimeplay** [ThunderTrooper/Bot-Trooper#1]
sorry im trying to use the cogs but the discord doesnt show cogs ill try again but pls help if you can

**Comment by ThunderTrooper** [comment]
it should
try typing the .load command

**Comment by pbprimeplay** [comment]
I followed you. Pls do the same if you understood what I meant

**Comment by ThunderTrooper** [comment]
ok, but maybe you should be using 3.8?
